### ISSUE TITLE
Crash under Linux - Unplayable

### ISSUE THREAD

**Issue by murkl** [ENSL/NS#114] opened 2021-07-25 09:31 UTC
Unfortunately with version 3.3b2 the game crashes under Linux (Steam) a few seconds after connect to a server or create an own one.

**Comment by pierow** [comment] 2021-10-31 23:31
Sorry about that. This should be fixed in the new version.

**Comment by murkl** [comment] 2021-11-02 17:47
Thanks for the new version. Unfortunately the game wont start now. I got a popup with Error: "could not load library /home/moritz/.local/share/Steam/steamapps/common/Half-Life/ns/cl_dlls/client.so"

But this file exists in exact the given path!

This is the console output:
```
~/.local/share/Steam/steamapps/common/Half-Life  ➤  ./hl.sh -game ns
Using breakpad crash handler
Setting breakpad minidump AppID = 70
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198170345949 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198170345949
GL_SIZES:  r:8 g:8 b:8 a:0 depth:24

could not load library /home/moritz/.local/share/Steam/steamapps/common/Half-Life/ns/cl_dlls/client.so`
```

**Comment by pierow** [comment] 2021-11-02 18:33
Sorry about this still being an issue. What linux distro are you using? I can try running it and look into what libraries are missing. For some reason half-life doesn't give descriptive library errors for the client when it can't load one but it does on the server.

Even once you get it running there will be some bugs with half-life as described here https://github.com/ENSL/NS/issues/7, so if you're looking for the optimal experience on linux it might actually be through proton, but I appreciate the feedback and help with getting this ironed out to run natively  on linux.

**Comment by pierow** [comment] 2021-11-04 03:28
I've been able to reproduce this on Ubuntu and it works if I build the game on Ubuntu instead of Debian.  The next patch at the very least will be built on Ubuntu instead of Debian for broader compatibility, but it's not an ideal solution.

If you'd like to test it out here are the binaries that worked for me.  Just apply it over the new version of the game. Note that trying to join a public server that is running the new version will stop you from connecting as the new binaries won't pass the consistency check against the server's.
[ns-linux-bin-test.zip](https://github.com/ENSL/NS/files/7472095/ns-linux-bin-test.zip)

**Comment by murkl** [comment] 2021-11-04 11:03
Thanks a lot! It's working with your binaries based on Ubuntu! I am using Arch Linux. I can confirm that the consistency check on a Server running 3.3b3 is working too. Can you figure out which libraries are needed?

**Comment by pierow** [comment] 2021-11-12 17:23
The new version is out which fixes this. I think it was because with the last version I was building with Debian and the 32 bit libraries are in different directories than Ubuntu, but I didn't get a chance to debug it. Prior to that it was config issues that are resolved. I don't doubt there's still work to be done to make the linux builds more compatible though. If you run into other issues or can offer guidance for making the linux builds better feel free to open another issue.

**Closed as completed by pierow** 2021-11-12 17:23 UTC
Labels: bug

**Comment by murkl** [comment] 2021-11-24 17:12
Thanks!! I can confirm that version 3.3 beta 4 is working fine now!
